on:
  push:
    branches:
      - 'main'

  pull_request:
    branches:
      - 'main'

env:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  IP_ADDRESS: ${{ secrets.IP_ADDRESS }}

jobs:
  check-docker:
    runs-on: ubuntu-24.04

    if: github.event_name == 'push'

    steps:
      - name: Make sure docker is running
        run: |
          echo "$SSH_PRIVATE_KEY" > ssh-private-key
          chmod 600 ssh-private-key
          ssh -i ssh-private-key -o StrictHostKeyChecking=no root@$IP_ADDRESS << 'EOF' 
            if ! (docker ps | grep -q "redis"); then
              cd /home/app; 
              docker-compose up -d; 
              docker ps | grep "redis"; 
            fi
          EOF
          rm -rf ssh-private-key

  deploy:
    needs: check-docker
    runs-on: ubuntu-24.04
    if: github.event_name == 'push'

    steps:
      # 1. Make sure to the runner's content matches the local content
      - name: Match runner's content with the local
        uses: actions/checkout@v5

      # 2. Install Java in runner's environment
      - name: Install Java
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'temurin'

      # DEBUG
      - name: Check file contents
        run: ls -aq

      - name: Check gradlew file
        run: cat ./gradlew

      # 3. Build JAR file
      - name: Build JAR file
        run: |
          chmod +x ./gradlew
          ./gradlew bootJar

      # 4. Deploy to VPS
      - name: Deploy to VPS
        run: |
          echo "$SSH_PRIVATE_KEY" > ssh-private-key
          chmod 600 ssh-private-key
          ssh -i ssh-private-key -o StrictHostKeyChecking=no root@$IP_ADDRESS << 'EOF'
            pkill -f "java" || true
          EOF
          scp -i ssh-private-key -o StrictHostKeyChecking=no build/libs/*.jar root@$IP_ADDRESS:/home/app
          rm -rf ssh-private-key*